let type = {
    CHANGE_LOCATION: 'CHANGE_LOCATION',
    START_SEARCH: 'START_SEARCH',
    UPDATE_FORECAST: 'UPDATE_FORECAST',
    UPDATE_MSG: 'UPDATE_MSG',
    DO_NOTHING: 'DO_NOTHING'
}

export default type;